// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSvnrkrT0MbJTu91Afm6VBdxr-AFDTgpM',
    appId: '1:144285173770:web:bba15a2e2f50b0f445b7f3',
    messagingSenderId: '144285173770',
    projectId: 'employee-db-4410c',
    authDomain: 'employee-db-4410c.firebaseapp.com',
    databaseURL: 'https://employee-db-4410c-default-rtdb.firebaseio.com',
    storageBucket: 'employee-db-4410c.firebasestorage.app',
    measurementId: 'G-0BK4E8CK37',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb_u7ML8OEnTIf8XTgifGckh4EMAul6I0',
    appId: '1:144285173770:android:82b039b335c7fafb45b7f3',
    messagingSenderId: '144285173770',
    projectId: 'employee-db-4410c',
    databaseURL: 'https://employee-db-4410c-default-rtdb.firebaseio.com',
    storageBucket: 'employee-db-4410c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBMVTyVg8etJQY7HquKIP58XSOmCoElxQ',
    appId: '1:144285173770:ios:8eeb011bedaca01545b7f3',
    messagingSenderId: '144285173770',
    projectId: 'employee-db-4410c',
    databaseURL: 'https://employee-db-4410c-default-rtdb.firebaseio.com',
    storageBucket: 'employee-db-4410c.firebasestorage.app',
    iosBundleId: 'com.example.employee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBMVTyVg8etJQY7HquKIP58XSOmCoElxQ',
    appId: '1:144285173770:ios:8eeb011bedaca01545b7f3',
    messagingSenderId: '144285173770',
    projectId: 'employee-db-4410c',
    databaseURL: 'https://employee-db-4410c-default-rtdb.firebaseio.com',
    storageBucket: 'employee-db-4410c.firebasestorage.app',
    iosBundleId: 'com.example.employee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSvnrkrT0MbJTu91Afm6VBdxr-AFDTgpM',
    appId: '1:144285173770:web:f54bf8d445dc34ea45b7f3',
    messagingSenderId: '144285173770',
    projectId: 'employee-db-4410c',
    authDomain: 'employee-db-4410c.firebaseapp.com',
    databaseURL: 'https://employee-db-4410c-default-rtdb.firebaseio.com',
    storageBucket: 'employee-db-4410c.firebasestorage.app',
    measurementId: 'G-J5Z4XQL4BC',
  );
}
